### ISSUE TITLE
Omezená maximální délka hesla

### ISSUE THREAD

**Issue by Su5hicz** [Firu115/jako_pavouk#1]
Ahoj,

První věc, super appka.

Bohužel nemám čas procházet kód, každopádně jsem narazil na podobný problém který má bohužel většina webových aplikací.

Frontend mě nechá vložit dlouhé heslo, kolem 30 znaků, jak při registraci tak resetu hesla, ale když se s ním snažím přihlásit, tvrdí že je špatně. Problém se vyřeší v momentě kdy zkrátím heslo třeba na 14 znaků.

Takže počítám s tím že někde v backendu, nejspíše před databází se to dlouhé heslo nezpracuje správně, samozřejmě doufám že se nakonec v DB hashuje takže jeho délka by neměla vadit. 
Pokud tomu tak je odhadl bych to na omezení datového typu někde mezi databázi a webovkou.

Nejjednodušší řešení by bylo alespoň informovat o maximální délce hesla při jeho zadání.

**Comment by Su5hicz** [comment]
Přece mi to nedalo, 

Po nějaké lehké orientaci v kódu. myslím že chyba bude v **router.go:43**

```	
bodyRegistrace struct {
		Email string `json:"email" validate:"required,email"`
		Jmeno string `json:"jmeno" validate:"required,min=3,max=16"`
		Heslo string `json:"heslo" validate:"required,min=5,max=128"`
	}

bodyPrihlaseni struct {
		EmailNeboJmeno string `json:"email" validate:"required"`
		Heslo          string `json:"heslo" validate:"required,min=5,max=25"`
```

Kdy pro tělo registrace je povoleno 128 znaků, ale přihlášení jen 25.

**Comment by firu11** [comment]
Ahoj, vážím si toho že aplikaci využíváš a ještě pomáháš zlepšovat. 

Trochu jsem si četl o bcrypt limitacích a zjistil jsem, že funguje jen pro max. 72 bytů. 

Prozatím jsem tedy nastavil maximální délku na 72 znaků a heslo omezil pouze na ASCII znaky, které zabírají max. 1 byte a tak 72 bytů = 72 znaků. e7c472b

V budoucnu bych to nějak vylepšil. (https://www.monterail.com/blog/more-secure-passwords-bcrypt)
